name: Kaiwa
options:
  bundleIdPrefix: to.yumi
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
settings:
  SWIFT_VERSION: "5.9"
targets:
  Kaiwa:
    type: application
    platform: iOS
    sources:
      - Kaiwa
    settings:
      INFOPLIST_FILE: Kaiwa/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: to.yumi.kaiwa
      DEVELOPMENT_TEAM: AN5KM8QGEF
      MARKETING_VERSION: "0.1.0"
      CURRENT_PROJECT_VERSION: "4"
      TARGETED_DEVICE_FAMILY: "1,2"
      SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: "NO"
    info:
      path: Kaiwa/Info.plist
      properties:
        CFBundleName: Kaiwa
        CFBundleDisplayName: Kaiwa
        CFBundleShortVersionString: "${MARKETING_VERSION}"
        CFBundleVersion: "${CURRENT_PROJECT_VERSION}"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: "Kaiwa needs microphone access to transcribe and translate conversations in real-time."
        UIRequiresFullScreen: true
