name: Kaiwa
options:
  bundleIdPrefix: com.kaiwa
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
settings:
  SWIFT_VERSION: "5.9"
packages:
  ClerkKit:
    url: https://github.com/clerk/clerk-ios
    from: "1.0.0"
targets:
  Kaiwa:
    type: application
    platform: iOS
    sources:
      - Kaiwa
    settings:
      INFOPLIST_FILE: Kaiwa/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.kaiwa.app
      MARKETING_VERSION: "1.0.0"
      CURRENT_PROJECT_VERSION: "1"
      TARGETED_DEVICE_FAMILY: "1,2"
      SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: "NO"
    dependencies:
      - package: ClerkKit
        product: ClerkKit
      - package: ClerkKit
        product: ClerkKitUI
    info:
      path: Kaiwa/Info.plist
      properties:
        CFBundleName: Kaiwa
        CFBundleDisplayName: 会話
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: "Kaiwa needs microphone access to transcribe and translate conversations in real-time."
        UIRequiresFullScreen: true
