name: Kaiwa
options:
  bundleIdPrefix: to.yumi
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
settings:
  SWIFT_VERSION: "5.9"
packages:
  ClerkKit:
    url: https://github.com/clerk/clerk-ios
    from: "1.0.0"
targets:
  Kaiwa:
    type: application
    platform: iOS
    sources:
      - Kaiwa
    settings:
      INFOPLIST_FILE: Kaiwa/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: to.yumi.kaiwa
      DEVELOPMENT_TEAM: AN5KM8QGEF
      CODE_SIGN_STYLE: Automatic
      MARKETING_VERSION: "0.1.0"
      CURRENT_PROJECT_VERSION: "4"
      TARGETED_DEVICE_FAMILY: "1,2"
      SUPPORTS_XR_DESIGNED_FOR_IPHONE_IPAD: "NO"
    dependencies:
      - package: ClerkKit
        product: ClerkKit
      - package: ClerkKit
        product: ClerkKitUI
  KaiwaTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - KaiwaTests
    dependencies:
      - target: Kaiwa
    info:
      path: Kaiwa/Info.plist
      properties:
        CFBundleName: Kaiwa
        CFBundleDisplayName: Kaiwa
        CFBundleShortVersionString: "${MARKETING_VERSION}"
        CFBundleVersion: "${CURRENT_PROJECT_VERSION}"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
        NSMicrophoneUsageDescription: "Kaiwa needs microphone access to transcribe and translate conversations in real-time."
        UIRequiresFullScreen: true
